services:
  app:
    image: project-app:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    networks:
      - app-network

  nginx:
    image: project-nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
    networks:
      - app-network

networks:
  app-network:
    driver: overlay